name: Create Release on Tag

on:
  push:
    tags:
      - 'v*' #trigger on pushed tag with 'v' in name

permissions:
  contents: write # required to be able to add release 

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare and Zip Project
        run: | #Get the target tag, create a release directory, copy the files from /src/ to release, and finaly zip it. 
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          RELEASE_PROJECT_NAME="course-customizer-php8.1"
          
          echo "Preparing release archive for: $RELEASE_PROJECT_NAME Version $TAG_NAME"

          mkdir "$RELEASE_PROJECT_NAME"

          rsync -av ./src/ README* LICENSE* "$RELEASE_PROJECT_NAME" 

          zip -r "${RELEASE_PROJECT_NAME}.zip" "$RELEASE_PROJECT_NAME"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.zip # Uploads the zip created in the previous step
          generate_release_notes: true # Auto-generates changelog based on PRs
